### ISSUE TITLE
PV-Nutzung konventioneller Strom

### ISSUE THREAD

**Issue by raphael0612** [simonschaluppe/pyped#34]
![image](https://user-images.githubusercontent.com/75998439/102106245-a014c480-3e30-11eb-96d7-8e7d2fb0a855.png)
Wert wenn wahr sollte Null sein (kein Strombezug, wenn PV größer als E-cars HHS und HS+Klimaanlage)

**Comment by simonschaluppe** [comment]
ah schau ich mir gleich an
