### ISSUE TITLE
Reststrom Netzstrom bezogen ges FW, Erdg: Hilfsstrom doppelt

### ISSUE THREAD

**Issue by raphael0612** [simonschaluppe/pyped#35]
Netzstrom besteht aus "Haushaltstrom", "e-cars" und "Hilfsstrom und Klimaanlage".
![image](https://user-images.githubusercontent.com/75998439/102112570-2da7e280-3e38-11eb-8e01-ddd7a815893d.png)
"Haushaltsstrom" bzw. "Nutzerstrom" beinhalten den "Hilfsstrom und Klimaanlage" schon (zwar t-1, kommt aber aufs selbe raus), somit wird Hilfsstrom und Klimaanlage zweimal zum Netzstrom (Reststrom konventionelle Betrachtung) gerechnet.
![image](https://user-images.githubusercontent.com/75998439/102113068-dd7d5000-3e38-11eb-8544-45286400f0bd.png)
![image](https://user-images.githubusercontent.com/75998439/102113128-f2f27a00-3e38-11eb-8079-7e12250e6a02.png)

**Comment by simonschaluppe** [comment]
Werde das analog zur erneuerbaren Deckung lösen
@zelgerthomas  gibts da was zu beachten hinsichtlich auswertung?

**Comment by simonschaluppe** [comment]
fix: Hilfsttrom aus Nutzerstrom rausgenommen.

![grafik](https://user-images.githubusercontent.com/22156735/102144844-770f2680-3e66-11eb-8542-68610363572c.png)
