### ISSUE TITLE
dashboard und ergebnisse Konventionell /erneuerbar bei ALLES aus passen nicht zusammen

### ISSUE THREAD

**Issue by simonschaluppe** [simonschaluppe/pyped#47]
vermutlich nur ein darstellungsproblem

![grafik](https://user-images.githubusercontent.com/22156735/102284721-fc610c80-3f34-11eb-9fa0-c1d464ca7476.png)

**Comment by simonschaluppe** [comment]
das ergebnisblatt hat noch einige probleme, grade in der ersten matrix

**Comment by raphael0612** [comment]
zum Thema Dashboard Darstellung und Ergebnisblatt: (ich hoffe das Thema passt unter dem issue)
Bezüglich Vergleich Endenergiebedarf/Überschüsse fehlt bei den konventionellen Varianten die PV-Nutzung
- ohne PV
![image](https://user-images.githubusercontent.com/75998439/102519139-680cbc00-4092-11eb-97f1-e3a2834a77c0.png)
- mit PV
![image](https://user-images.githubusercontent.com/75998439/102519291-94283d00-4092-11eb-8214-fbd27147384a.png)
ich denke, man kann den Wert unten einfach übernehmen?
![image](https://user-images.githubusercontent.com/75998439/102519550-eb2e1200-4092-11eb-92bf-df47289fb1f4.png)

**Comment by simonschaluppe** [comment]
das stimmt, da bin ich auch letztens drüber gestolpert, ich glaub beim Ergebnisse Blatt is generell einiges verloren gegangen.

Sollte aber in f4d4ec104bcdbb0fe3bb65b1595fdab22d1018ef  gelöst sein.
Besteht das problem in der aktuellsten, bzw der revision immer noch?

**Comment by simonschaluppe** [comment]
ah my bad, du hast es eh geschrieben
