### ISSUE TITLE
Anteil Lüfterstrom ohne KWL

### ISSUE THREAD

**Issue by raphael0612** [simonschaluppe/pyped#48]
![image](https://user-images.githubusercontent.com/75998439/102398016-02abc300-3fdf-11eb-83ea-342489f13ea0.png)
Der Formelteil bezüglich "Anteil Lüfterstrom ohne KWL"(CB6) sagt: wenn die Lüftungsanlage EIN ist, soll der Lüfterstrom mal 1 gerechnet werden, ansonsten mal dem "Anteil Lüfterstrom ohne KWL".
1. Ich dachte der "Anteil ..." gibt den Anteil der Lüftung ohne Wärmerückgewinnung an, denn den kann man sonst nirgends wählen?
2.  Warum soll der Lüfterstrom mit dem "Anteil ..." multipliziert werden, wenn die Lüftungsanlage AUS ist? Ich denke, wenn die Lüftungsanlage AUS ist benötigt man gar keinen Lüfterstrom.
3. Wenn die Lüftungsanlage EIN ist, sollte doch eher mit 1-"Anteil..." multipliziert werden. (kann ja sein, dass nicht der gesamte Lüftungsstrom gegeben ist oder benötigt wird)
Kompletten Lösungsvorschlag hab ich leider noch keinen, bzw. bin ich mir zu unsicher was gewollt ist.

**Comment by simonschaluppe** [comment]
Mein Verständnis ist, dass der Anteil Lüfterstrom ohne KWL der ist, der in jedem Fall anfällt / anfällen würde in Form von Abluftanlagen
@zelgerthomas plz confirm

![grafik](https://user-images.githubusercontent.com/22156735/102490140-b7d98c00-406e-11eb-95fb-cd084fc5963d.png)

**Comment by simonschaluppe** [comment]
KWL -> "Mit ohne WRG"
Dokumentieren und schließen
