### ISSUE TITLE
Lüftungswärmeverluste bilden entweder 0% WRG oder 100% WRG ab

### ISSUE THREAD

**Issue by raphael0612** [simonschaluppe/pyped#77]
In den Lüftungswärmeverlusten bzw. dem Lüftungsleitwert wird der Anteil an Lüftung mit/ohne WRG nicht berücksichtigt.
Der Leitwert berücksichtigt nur ob die Lüftungsanlage EIN (=Anlagenluftwechsel mit 1-WRG multipliziert) oder AUS (=Anlagenluftwechsel mit 1 multipliziert) ist.
Unten die Formel für die Lüftungswärmeverluste
![image](https://user-images.githubusercontent.com/75998439/103217034-e5002700-4917-11eb-8e37-1bfff384bc66.png)
Die führen zur Formel für den Lüftungsleitwert
![image](https://user-images.githubusercontent.com/75998439/103217080-03662280-4918-11eb-8168-fbebe98a36e8.png)
Ich denke, wenn man die Wirkungsgrade der Rückgewinnungen mit (1-Anteil ohne WRG) multipliziert, ist der "Anteil an Lüftung mit WRG" korrekt dargestellt.
![image](https://user-images.githubusercontent.com/75998439/103217806-cc910c00-4919-11eb-9116-05a7f0d80f5a.png)

**Comment by raphael0612** [comment]
Eine Erklärung oder Beschriftung, dass die Checkbox "Lüftungsanlage" sagt, ob man eine Lüftung mit WRG oder eine Abluftanlage verwendet, wäre glaub ich auch hilfreich

**Comment by simonschaluppe** [comment]
ist das ein bug, der zu falschen ergebnissen führt? wenn ja, bitte beispiel anhängen.

die formeln in HW bis HX werden "nur" zur neuerlichen Berechnung der Vergleichsvarianten "konventionell", also OHNE DSM für den Vergleich der Wärmebilanz verwendet.

für die berechnung der meisten ergebnisse im Dashboard und Ergebnisse blatt wird QV hier berechnet, der "1-" wird berücksichtigt: 
Die Formel besagt: QV = luftwechsel_infiltration + luftwechsel_lüftung * (1 - Anteil WRG), 
wenn keine Lüftung dann:  QV = luftwechsel_infiltration + luftwechsel_lüftung * (1 ) 
von daher: ja, "Lüftung" werde ich entsprechend umbenennen und dokumentieren

![grafik](https://user-images.githubusercontent.com/22156735/103249123-0d1a7500-496e-11eb-80a0-186f5778c5db.png)

**Comment by simonschaluppe** [comment]
folgende Formel würde das problem bei den thermisch effektiven Luftwechsel beheben:
![grafik](https://user-images.githubusercontent.com/22156735/103250842-35a66d00-4976-11eb-9502-5c060042c95e.png)

**Comment by simonschaluppe** [comment]
Formel für den el lüfterstrom passt ?
Luftwechsel immer gleich, wenn "Lüftung AUS", dann auch zumindest für den anteil MIT WRG KEIN strom. dh, das system wäre dann gar nicht da, der luftwechsel aber schon. fensterlüftung?
