### ISSUE TITLE
wärmebrückenzuschlag derzeit nicht verwendet

### ISSUE THREAD

**Issue by simonschaluppe** [simonschaluppe/pyped#78]
![grafik](https://user-images.githubusercontent.com/22156735/103352804-88cc0d00-4aa7-11eb-92e0-cfa76fad9fe8.png)

**Comment by raphael0612** [comment]
für den Transmissionswert wirds hier verwendet oder?
![image](https://user-images.githubusercontent.com/75998439/103407364-bf189380-4b5e-11eb-8bde-be224fb79097.png)
