### ISSUE TITLE
Variantenberechnung mit Lüftung detailliert

### ISSUE THREAD

**Issue by raphael0612** [simonschaluppe/pyped#82]
In der Variantenberechnung bleiben die Lüftungsverluste und damit "Mindestheizen thermisch" an die Detaileingabe der Lüftung gebunden.
![image](https://user-images.githubusercontent.com/75998439/103461246-309e4080-4d1d-11eb-8642-9c1da5ddbe54.png)
![image](https://user-images.githubusercontent.com/75998439/103461259-490e5b00-4d1d-11eb-8199-9381b0c86595.png)

Einfach gesagt, den Anteil WRG usw. (Detaileingabe) kann man noch nicht variieren. Das war dir wsl schon bewusst aber ich kann die Variantenberechnung so halt nur sehr eingeschränkt verwenden.

**Comment by simonschaluppe** [comment]
hm, das ist leider ein problem, das sich nicht unmittelbar komplett auflösen lässt.
prinzipiell müsste jeder parameter, ob allgemein oder detailliert in der variantenbeschreibung auch sein, damit er dort auch variiert werden kann. das wüde in dem Fall 6 (nutzungen) x 5 (variablen) = 30 spalten bedeuten. 
das ändert die Struktur des excels und ist nicht mehr mit früheren versionen kompatibel. das würde ich daher erst für den winter release mitte februar so umbauen.

Bis dahin würde ich vorschlagen, dass die detaileingabe auch berücksichtig ob varianten modus oder nicht, und in ersterem fall einfach die allgemeinen Faktoren aus dem Variantenblatt verwendet.
wäre das für deine ZWecke ok? oder wär für dich die nutzungsspezifische WRG eingabe hilfreich?

**Comment by raphael0612** [comment]
Wenn ich das richtig verstehe, dass ich dann in der Detaileingabe entscheiden kann ob eben diese oder die allgemeinen Faktoren für die Varianten verwendet werden, dann würd das mMn gut passen.

**Comment by simonschaluppe** [comment]
ok passt , das lässt sich relativ einfach machen, mit eiem zusäzlichen feld in der varianten definition "detaileingabe lüftung verwenden" > "Wahr" > verhalten wie davor , "Falsch" > nutzungs**un**spezifische faktoren der varianten sim werden verwendet
